apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: https-port
      port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}